apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orderservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: orderservice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orderservice
                port:
                  number: 8000
