global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orderservice'
    static_configs:
      - targets: ['orderservice:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
